### ISSUE TITLE
Error on audacity 2.4.1 on audacity.cfg read

### ISSUE THREAD

**Issue by marlon-sousa** [paulber19/audacityAccessEnhancementNVDAAddon#1]
Hello,

Apparently audacity.cfg is not being parsed correctly on audacity 2.4.1.

I have cleaned my audacity installation and have had errors regarding audacity.cfg read by the addon:

error: cannot read C:\Users\[xxx]\AppData\Roaming\audacity\audacity.cfg file
WARNING - external:appModules.audacity.au_applicationSettings.SettingsFileHandler._load (09:13:55.485) - MainThread (5488):

To further debug I added the error description on the corresponding log.warning line in au_applicationSettings.py

Line 85:
log.warning("error: cannot read %s file"%self.filePath)
line 86 (new) 
log.debug(f"{e}")

I urge you please to include this line as it would have saved me lots of times when debugging this up front.

Anyways, looking at the log viewer again showed a more interesting error:

Duplicate section name at line 25.

I then went to the audacity.cfg file and checked line 25. Here is what I got:
[MenuBar]

Strangely enough, I looked for menubar because this was the duplicated section. And, in line  3, I found the following:

MenuBar=File,Edit,Select,View,Transport,Tracks,Generate,Effect,Analyze,Tools,Optional,Help

I don't know if this schema is found before 2.4.1, but it seems that there are now ini and conf style keys mixed in the same file
I don't know if ConfigObj can deal with this kind of files either ... apparently not (https://github.com/DiffSK/configobj/pull/135) but I fear that, if we don't find a way to overcome this, your addon won't be usable in current versions of audacity.

A good option would be to set defaults and should errors arise when reading the cfg file just warn the user and user that defaults.

However, consider using another ini parser that is more tolerant.

If you need further help or are whiling to accept pull requests drop me a note and I will try to help.

**Comment by paulber19** [comment]
Hi Marlon.
Thank you for your question and your analysis of the problem.
Indeed, the add-on is not compatible today with the latest version of 
Audacity.
For the past week, I've been working on it.
But since there is not only the problem of the audacity.cfg file, it 
takes time and I do not work on it full time.
For now, if you want to use the add-on, you must stay with version 2.3.3 
of Audacity.
Otherwise and if you absolutely want to use the latest version of 
Audacity, I attach the last version under development.

Please inform me of any malfunctions found with this version.

Best regards.
Paul.
